/*
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * IA-64 firmware behavior flags.
 */

#ifndef HW_IA64_FIRMWARE_COMPAT_H
#define HW_IA64_FIRMWARE_COMPAT_H

#define IA64_FW_COMPAT_LOADER_DIRECT_ALIAS (1ULL << 0)
#define IA64_FW_LOADER_DIRECT_ALIAS_OFFSET  0x0000000080000000ULL
#define IA64_FW_COMPAT_FIXED_LOADER_WINDOWS (1ULL << 1)
#define IA64_FW_COMPAT_SPARSE_SAL_MDT      (1ULL << 2)
#define IA64_FW_COMPAT_SAL_CODE_GP         (1ULL << 3)
/* Legacy raw firmware only; ELF firmware always combines runtime sections. */
#define IA64_FW_COMPAT_COMBINED_RUNTIME    (1ULL << 4)
#define IA64_FW_COMPAT_ALL_MASK \
    (IA64_FW_COMPAT_LOADER_DIRECT_ALIAS | \
     IA64_FW_COMPAT_FIXED_LOADER_WINDOWS | \
     IA64_FW_COMPAT_SPARSE_SAL_MDT | \
     IA64_FW_COMPAT_SAL_CODE_GP | \
     IA64_FW_COMPAT_COMBINED_RUNTIME)

#endif /* HW_IA64_FIRMWARE_COMPAT_H */
